-- this has been generated by an llm, seems to work okay-ish for fachbeschreibungen

local function cell_text_length(cell)
  local text = pandoc.utils.stringify(cell)
  return utf8.len(text) or string.len(text)
end

local function update_width(widths, index, length)
  if not widths[index] or length > widths[index] then
    widths[index] = length
  end
end

function Table(tbl)
  local col_count = #tbl.colspecs

  if col_count == 0 then
    return tbl
  end

  local widths = {}

  -- Initialize with a small minimum width
  for i = 1, col_count do
    widths[i] = 8
  end

  -- Measure header cells
  if tbl.head and tbl.head.rows then
    for _, row in ipairs(tbl.head.rows) do
      for i, cell in ipairs(row.cells) do
        update_width(widths, i, cell_text_length(cell))
      end
    end
  end

  -- Measure body cells
  if tbl.bodies then
    for _, body in ipairs(tbl.bodies) do
      for _, row in ipairs(body.body) do
        for i, cell in ipairs(row.cells) do
          update_width(widths, i, cell_text_length(cell))
        end
      end
    end
  end

  -- Measure footer cells, if present
  if tbl.foot and tbl.foot.rows then
    for _, row in ipairs(tbl.foot.rows) do
      for i, cell in ipairs(row.cells) do
        update_width(widths, i, cell_text_length(cell))
      end
    end
  end

  -- Prevent one very long column from taking everything
  for i = 1, col_count do
    if widths[i] < 8 then
      widths[i] = 8
    elseif widths[i] > 40 then
      widths[i] = 40
    end
  end

  -- Normalize widths so that they add up to 1.0
  local total = 0
  for i = 1, col_count do
    total = total + widths[i]
  end

  local colspecs = {}
  for i = 1, col_count do
    colspecs[i] = {
      pandoc.AlignLeft,
      widths[i] / total
    }
  end

  tbl.colspecs = colspecs
  return tbl
end